/** Human titles for failed checks, by check id. */
export const FAIL_TITLES: Record<string, string> = {
  "handshake.challenge-decode": "402 has no readable x402 challenge",
  "handshake.version": "Protocol version inconsistent",
  "handshake.cors-expose": "CORS on, but PAYMENT-REQUIRED not exposed to browsers",
  "handshake.cors-preflight": "CORS preflight blocks the payment header",
  "handshake.head": "HEAD served without payment",
  "handshake.latency": "Slow 402 (> 1s)",
  "schema.amount-field": "Wrong amount field name for the version",
  "schema.required-fields": "Required fields missing",
  "schema.network": "Network id in the wrong format",
  "schema.amount-format": "Amount not an atomic-unit integer string",
  "schema.timeout": "maxTimeoutSeconds out of range",
  "schema.eip712-extra": "extra.name / extra.version missing",
  "schema.svm-feepayer": "Solana extra.feePayer missing",
  "schema.resource": "resource.url missing",
  "schema.resource-url": "resource URL doesn't match the endpoint",
  "schema.scheme": "Unknown payment scheme",
  "schema.accepts": "accepts[] empty",
  "schema.extra": "extra not an object",
  "schema.transfer-method": "Invalid assetTransferMethod",
  "asset.eip712-domain": "EIP-712 domain (extra.name/version) doesn't match the token",
  "asset.exists": "Asset contract/mint not on the declared network",
  "asset.eip3009": "Token doesn't support EIP-3009 (needs permit2)",
  "asset.address": "Asset isn't a valid token address",
  "asset.decimals": "Token doesn't answer decimals()",
  "asset.price-sanity": "Price looks mis-scaled",
  "asset.checksum": "Asset address checksum invalid",
  "asset.permit2-proxy": "Permit2 spender isn't the x402 proxy",
  "asset.permit2-deployed": "Permit2/x402 proxy not deployed on chain",
  "asset.svm-feepayer": "Invalid Solana feePayer",
  "payTo.valid": "payTo invalid (zero, wrong chain format, or a contract like the token)",
  "payTo.checksum": "payTo checksum invalid",
  "payTo.contract": "payTo is a contract",
  "facilitator.supported": "Facilitator doesn't support the scheme/network",
  "facilitator.feepayer": "feePayer isn't the facilitator's",
};

/** Some checks mean something different when they warn rather than fail. */
export const WARN_TITLES: Record<string, string> = {
  "handshake.cors-expose": "No CORS on the 402, or PAYMENT-RESPONSE not exposed",
  "handshake.version": "Legacy v1, or header/body version disagree",
  "schema.network": "Network id not strict CAIP-2 / unrecognized",
  "schema.amount-format": "Amount is zero or has leading zeros",
  "schema.transfer-method": "Non-spec assetTransferMethod extension",
  "schema.required-fields": "Non-critical required fields missing (e.g. maxTimeoutSeconds, description)",
};
